spring.application.name=Master
spring.datasource.url=jdbc:postgresql://localhost:5432/BancoMaster
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
server.port=8080
